[package]
name = "rotmg_extractor"
version = "0.1.0"
authors = ["Dominic Marcuse <dominic@marcuse.us>"]
edition = "2018"

[dependencies]
tempfile = "3.0.7"
tar = "0.4.22"
libflate = "0.1.21"
log = "0.4.6"
failure = "0.1.5"
failure_derive = "0.1.5"

# for extracting mappings
rotmg_networking = { path = "../rotmg_networking", optional = true }
regex = { version = "1.1.6", optional = true }
lazy_static = { version = "1.3.0", optional = true }
bimap = { version = "0.3.1", optional = true }

[features]
mappings = [ "rotmg_networking", "regex", "lazy_static", "bimap" ]
default = [ "mappings" ]

[dev-dependencies]
simple_logger = "1.0.1"
