[package]
name = "rotmg_extractor"
version = "0.1.0"
authors = ["Dominic Marcuse <dominic@marcuse.us>"]
edition = "2018"
license = "AGPL-3.0-or-later"

[dependencies]
tempfile = "3.0"
tar = "0.4"
libflate = "0.1"
log = "0.4"
failure = "0.1"
failure_derive = "0.1"
swf-tree = "0.6"
swf-parser = "0.5"

# for extracting mappings
rotmg_networking = { path = "../rotmg_networking", optional = true }
regex = { version = "1.1", optional = true }
lazy_static = { version = "1.3", optional = true }
bimap = { version = "0.3", optional = true }

[features]
mappings = [ "rotmg_networking", "regex", "lazy_static", "bimap" ]
default = [ "mappings" ]

[dev-dependencies]
simple_logger = "1.0"
