[package]
name = "rotmg_data"
version = "0.1.0"
authors = ["Dominic Marcuse <dominic@marcuse.us>"]
edition = "2018"
license = "AGPL-3.0-or-later"

[dependencies]
serde = { version = "1.0", features = [ "derive" ] }
num = "0.2"
